name: "CI Pipeline"

on:
  # This workflow runs every time you push code to main/master or depende nmo unsa na branch imo eh add sa array
  push:
    branches: [main, master]

  # This workflow runs for pull requests targeting main or master
  pull_request:
    branches: [main, master]

# Checklist like cpu scheduling murag steps ba onsa una ang ipa dagan like imo sa eh test, build dayun deploy kung walay errors
jobs:
  test:
    # Purpose ani kay during workflow mo create og virtual machine sa github nya adto padaganon ang workflow 
    runs-on: ubuntu-latest

    steps:
      # Kani mga names log names rani sia like indicator if unsa na nga steps ang currentlly nag dagan
      # Kaning uses actions naa rani sia sa github mura nig plugins  
      # ang repo sa github iya i download para ma access sa virtual machine nga gi create sa github
      # if wala ni siya ang virtual machine walay solod
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '22'

      # TAKE NOTE: dapat naa ang package.json before install sa dependencies
      # The reason why ngano 'run' kay para maka command ta sa virtual machine na terminal automatically by github
      - name: Install Dependencies
        run: npm ci 

      - name: Lint tests
        run: npm run lint

      - name: Vitest
        run: npm run test

      - name: Build
        run: npm run build